### ISSUE TITLE
Cannot find module 'leaflet'.

### ISSUE THREAD

**Issue by mohammadjalili** [elasticrash/ngx.leaflet.component#129]
hi 
i install ngx.leaflet.component , but i get this error

> ERROR in node_modules/ngx.leaflet.components/src/map/map.d.ts(4,20): error TS2307: Cannot find module 'leaflet'.

how can fix it? 

import systemJs ? @elasticrash

**Comment by elasticrash** [comment]
First of all, which version of angular are you using and how are you actually importing the module/library. This library also expects leaflet to be already on your package.json

This projects needs to be brought a bit up to date and maybe use a more modern way to package the library

**Comment by mohammadjalili** [comment]
i use angular 6.0.1

**Comment by elasticrash** [comment]
Ill try to use it in an angular 6 project later today, to see if there are any incompatibilities.

**Comment by elasticrash** [comment]
you basically need to do an 
npm install leaflet --save
because I am not including leaflet in my library ( I mention that somewhere)
but to spare you the trouble you also need rxjs in compatibility mode (cause I am not supporting angular 6 directly)
npm install rxjs@6 rxjs-compat@6 --save
I think I might update the lib to be angular6 compatible 

and works fine :D
